// AP and PP are defined in data.js (auto-generated by scraper.py)
let prevView = 'home';

// ── ARTICLES ───────────────────────────────────────────────────────────────────
// Update these with real article URLs and content as needed
// Update these with real article URLs as Diamond Index grows
const ARTICLES = [
  {
    tag: 'Player Analysis',
    title: 'Burwell & Mercado Are Redefining What Elite Looks Like in the SEC',
    meta: 'Diamond Index · 2025–26 Season',
    emoji: '◆',
    url: 'https://highschoolsports.nj.com/baseball',
  },
  {
    tag: 'Pitching Report',
    title: 'The Case for Pontoriero: ERA Under 1.00 Through 15+ Innings',
    meta: 'Diamond Index · 2025–26 Season',
    emoji: '◆',
    url: 'https://highschoolsports.nj.com/baseball',
  },
  {
    tag: 'Team Rankings',
    title: 'wRC+ Power Rankings: Which SEC Team Has the Most Dangerous Lineup?',
    meta: 'Diamond Index · 2025–26 Season',
    emoji: '◆',
    url: 'https://highschoolsports.nj.com/baseball',
  },
];

// ── STANDARD STAT CONFIGS ─────────────────────────────────────────────────────
const HIT_STD_COLS = ['AB','R','H','B2','B3','HR','RBI','BB','HBP','SB','AVG','OBP','SLG','OPS'];
const HIT_STD_CFG  = {
  AB:  { label:'AB',  fmt: v => v,           tip:'At Bats' },
  R:   { label:'R',   fmt: v => v,           tip:'Runs Scored' },
  H:   { label:'H',   fmt: v => v,           tip:'Hits' },
  B2:  { label:'2B',  fmt: v => v,           tip:'Doubles' },
  B3:  { label:'3B',  fmt: v => v,           tip:'Triples' },
  HR:  { label:'HR',  fmt: v => v,           tip:'Home Runs' },
  RBI: { label:'RBI', fmt: v => v,           tip:'Runs Batted In' },
  BB:  { label:'BB',  fmt: v => v,           tip:'Walks' },
  HBP: { label:'HBP', fmt: v => v,           tip:'Hit By Pitch' },
  SB:  { label:'SB',  fmt: v => v,           tip:'Stolen Bases' },
  AVG: { label:'AVG', fmt: v => v.toFixed(3).replace(/^0/,''), tip:'Batting Average' },
  OBP: { label:'OBP', fmt: v => v.toFixed(3).replace(/^0/,''), tip:'On-Base Percentage' },
  SLG: { label:'SLG', fmt: v => v.toFixed(3).replace(/^0/,''), tip:'Slugging Percentage' },
  OPS: { label:'OPS', fmt: v => v.toFixed(3), tip:'On-Base Plus Slugging' },
};

const PIT_STD_COLS = ['IP','W','L','H','R','ER','BB','K','HB','ERA','WHIP'];
const PIT_STD_CFG  = {
  IP:   { label:'IP',   fmt: v => v.toFixed(1),  lowerBetter:false, tip:'Innings Pitched' },
  W:    { label:'W',    fmt: v => v,              lowerBetter:false, tip:'Wins' },
  L:    { label:'L',    fmt: v => v,              lowerBetter:true,  tip:'Losses' },
  H:    { label:'H',    fmt: v => v,              lowerBetter:true,  tip:'Hits Allowed' },
  R:    { label:'R',    fmt: v => v,              lowerBetter:true,  tip:'Runs Allowed' },
  ER:   { label:'ER',   fmt: v => v,              lowerBetter:true,  tip:'Earned Runs' },
  BB:   { label:'BB',   fmt: v => v,              lowerBetter:true,  tip:'Walks' },
  K:    { label:'K',    fmt: v => v,              lowerBetter:false, tip:'Strikeouts' },
  HB:   { label:'HBP',  fmt: v => v,              lowerBetter:true,  tip:'Hit Batters' },
  ERA:  { label:'ERA',  fmt: v => v.toFixed(2),   lowerBetter:true,  tip:'Earned Run Average' },
  WHIP: { label:'WHIP', fmt: v => v.toFixed(2),   lowerBetter:true,  tip:'Walks + Hits per IP' },
};

// Track which mode each leaderboard is in
let hitMode = 'advanced'; // 'standard' | 'advanced'
let pitMode = 'advanced';
let hitPage = 1;
let pitPage = 1;
const LEADER_PAGE_SIZE = 100;
const GRADE_VALUES = ['Freshman', 'Sophomore', 'Junior', 'Senior'];
let playerLogsLoadPromise = null;

// Standard sort state
let hitStdSort = { col: 'HR', asc: false };
let pitStdSort = { col: 'K',  asc: false };

function setHitStdSort(col) {
  if (hitStdSort.col === col) hitStdSort.asc = !hitStdSort.asc;
  else hitStdSort = { col, asc: HIT_STD_CFG[col]?.lowerBetter ?? false };
  hitPage = 1;
  renderHitTable();
}

function setPitStdSort(col) {
  if (pitStdSort.col === col) pitStdSort.asc = !pitStdSort.asc;
  else pitStdSort = { col, asc: PIT_STD_CFG[col]?.lowerBetter ?? false };
  pitPage = 1;
  renderPitchTable();
}

// ── STAT TOOLTIPS ──────────────────────────────────────────────────────────────
const HIT_TIPS = {
  PS:       'Player Score — 0-100 composite from qualified-player percentiles',
  wRC_plus: 'Weighted Runs Created Plus — 100 is avg, higher is better',
  wOBA:     'Weighted On-Base Average — measures overall offensive value',
  OPS:      'On-Base Plus Slugging',
  AVG:      'Batting Average',
  SLG:      'Slugging Percentage',
  OBP:      'On-Base Percentage',
  ISO:      'Isolated Power — SLG minus AVG',
  BsR:      'Baserunning Runs — value of stolen bases & triples',
  wRAA:     'Weighted Runs Above Average',
  wRC:      'Weighted Runs Created',
  BB_pct:   'Walk Percentage',
};

const PIT_TIPS = {
  PS:        'Player Score — 0-100 composite from qualified-pitcher percentiles',
  ERA:       'Earned Run Average — per 7 innings (high school standard)',
  FIP:       'Fielding Independent Pitching — strikeouts, walks, HBP only',
  WHIP:      'Walks + Hits per Inning Pitched',
  K7:        'Strikeouts per 7 innings',
  BB7:       'Walks per 7 innings',
  KBB:       'Strikeout-to-Walk Ratio',
  ERA_minus: 'ERA- — 100 is avg, lower is better',
  FIP_minus: 'FIP- — 100 is avg, lower is better',
  RAA:       'Runs Above Average',
  IP:        'Innings Pitched',
  K:         'Total Strikeouts',
};

// ── HELPERS ────────────────────────────────────────────────────────────────────
function pc(p) {
  if (p >= 90) return '#C89B3C';
  if (p >= 75) return '#b8863a';
  if (p >= 58) return '#7a6035';
  if (p >= 42) return '#5C677D';
  if (p >= 25) return '#3a6ea8';
  return '#2a5080';
}

function calcPct(vals, v, lowerBetter) {
  const sorted = [...vals].sort((a, b) => a - b);
  const b = sorted.filter(x => x < v).length;
  const e = sorted.filter(x => x === v).length;
  const raw = sorted.length ? Math.round(((b + e * 0.5) / sorted.length) * 100) : 50;
  return lowerBetter ? 100 - raw : raw;
}

function normalizeGrade(value) {
  const raw = String(value || '').trim().toLowerCase();
  return GRADE_VALUES.find(g => g.toLowerCase() === raw) || '';
}

function isPositionText(value) {
  const raw = String(value || '').trim();
  if (!raw) return false;
  return /^[A-Z0-9,\s/.-]+$/.test(raw) && /[A-Z]/.test(raw);
}

function normalizePlayerIdentity(p) {
  if (!p) return;

  p.name = String(p.name || '')
    .replace(/\s+(?:#|\/)\d+\s*$/g, '')
    .replace(/\s+/g, ' ')
    .trim();

  const trailingGrade = p.name.match(/\s+(Freshman|Sophomore|Junior|Senior)$/i);
  if (trailingGrade) {
    const grade = normalizeGrade(trailingGrade[1]);
    p.name = p.name.slice(0, trailingGrade.index).trim();
    if (!normalizeGrade(p.year)) {
      if (isPositionText(p.year) && !p.pos) p.pos = p.year;
      p.year = grade;
    }
  }

  const normalizedYear = normalizeGrade(p.year);
  if (normalizedYear) p.year = normalizedYear;
}

function normalizePlayers() {
  AP.forEach(normalizePlayerIdentity);
  PP.forEach(normalizePlayerIdentity);
}

function setupPlayerScore() {
  HSC.PS = { label:'PS', fmt: v => v.toFixed(1) };
  PSC.PS = { label:'PS', fmt: v => v.toFixed(1), lowerBetter:false };

  const replaceStat = (arr, from, to) => {
    const idx = arr.indexOf(from);
    if (idx >= 0) arr.splice(idx, 1, to);
  };
  const removeStat = (arr, stat) => {
    const idx = arr.indexOf(stat);
    if (idx >= 0) arr.splice(idx, 1);
  };
  replaceStat(HIT_TABLE_COLS, 'OFF', 'PS');
  replaceStat(PIT_TABLE_COLS, 'WAR', 'PS');
  HIT_PCT_GROUPS.forEach(g => removeStat(g.stats, 'OFF'));
  PIT_PCT_GROUPS.forEach(g => removeStat(g.stats, 'WAR'));

  const hitQualified = AP.filter(p => p.qualified);
  const pitQualified = PP.filter(p => p.qualPitch);
  const hitVals = stat => hitQualified.map(p => p[stat]).filter(Number.isFinite);
  const pitVals = stat => pitQualified.map(p => p[stat]).filter(Number.isFinite);

  const h = {
    wRC_plus: hitVals('wRC_plus'),
    wOBA: hitVals('wOBA'),
    OPS: hitVals('OPS'),
    ISO: hitVals('ISO'),
    BB_pct: hitVals('BB_pct'),
    BsR: hitVals('BsR'),
  };
  AP.forEach(p => {
    p.PS =
      calcPct(h.wRC_plus, p.wRC_plus, false) * 0.45 +
      calcPct(h.wOBA, p.wOBA, false) * 0.20 +
      calcPct(h.OPS, p.OPS, false) * 0.15 +
      calcPct(h.ISO, p.ISO, false) * 0.10 +
      calcPct(h.BB_pct, p.BB_pct, false) * 0.05 +
      calcPct(h.BsR, p.BsR, false) * 0.05;
  });

  const q = {
    ERA_minus: pitVals('ERA_minus'),
    FIP_minus: pitVals('FIP_minus'),
    WHIP: pitVals('WHIP'),
    K7: pitVals('K7'),
    KBB: pitVals('KBB'),
    IP: pitVals('IP'),
  };
  PP.forEach(p => {
    p.PS =
      calcPct(q.ERA_minus, p.ERA_minus, true) * 0.30 +
      calcPct(q.FIP_minus, p.FIP_minus, true) * 0.25 +
      calcPct(q.WHIP, p.WHIP, true) * 0.15 +
      calcPct(q.K7, p.K7, false) * 0.15 +
      calcPct(q.KBB, p.KBB, false) * 0.10 +
      calcPct(q.IP, p.IP, false) * 0.05;
  });
}

function resetHitPage() { hitPage = 1; renderHitTable(); }
function resetPitPage() { pitPage = 1; renderPitchTable(); }

function setLeaderPage(kind, page) {
  if (kind === 'hit') {
    hitPage = page;
    renderHitTable();
  } else {
    pitPage = page;
    renderPitchTable();
  }
}

function renderPagination(kind, total, page, pageSize) {
  const el = document.getElementById(kind === 'hit' ? 'hitPagination' : 'pitPagination');
  if (!el) return;
  if (!total) {
    el.innerHTML = '';
    return;
  }

  const pages = Math.max(1, Math.ceil(total / pageSize));
  const start = (page - 1) * pageSize + 1;
  const end = Math.min(total, page * pageSize);
  el.innerHTML = `
    <div class="pagination-info">Showing <span>${start}-${end}</span> of <span>${total}</span></div>
    <div class="pagination-actions">
      <button class="pagination-btn" onclick="setLeaderPage('${kind}', 1)" ${page <= 1 ? 'disabled' : ''}>First</button>
      <button class="pagination-btn" onclick="setLeaderPage('${kind}', ${page - 1})" ${page <= 1 ? 'disabled' : ''}>Previous</button>
      <span>Page ${page} of ${pages}</span>
      <button class="pagination-btn" onclick="setLeaderPage('${kind}', ${page + 1})" ${page >= pages ? 'disabled' : ''}>Next</button>
      <button class="pagination-btn" onclick="setLeaderPage('${kind}', ${pages})" ${page >= pages ? 'disabled' : ''}>Last</button>
    </div>`;
}

function teamLogo(team, size = 16) {
  const m = TM[team];
  if (m && m.logo) return `<img src="${m.logo}" width="${size}" height="${size}" style="object-fit:contain;flex-shrink:0;border-radius:2px">`;
  return '';
}

function chip(team) {
  const m = TM[team] || { bg: '#111', s: '#333', t: '#aaa' };
  return `<span class="team-chip" style="background:${m.bg};color:${m.t};border:1px solid ${m.s}66">
    ${teamLogo(team, 14)}
    ${team}
  </span>`;
}

function playerCell(p) {
  const sub = [p.year, p.pos].filter(Boolean).join(' · ');
  return `<td class="player-cell">
    <div class="player-name">${p.name}</div>
    ${sub ? `<div class="player-sub">${sub}</div>` : ''}
  </td>`;
}

function pctRow(label, val, pctVal, fmtVal) {
  const clr = pc(pctVal);
  const textClr = pctVal >= 58 ? '#0B1F3A' : '#F8F9FA';
  return `<div class="pct-row">
    <span class="pct-label">${label}</span>
    <div class="pct-bar-outer">
      <div class="pct-bar-track">
        <div class="pct-bar-fill" style="width:${pctVal}%;background:${clr}"></div>
        <div class="pct-bubble" style="background:${clr};left:${pctVal}%;color:${textClr}">${pctVal}</div>
      </div>
    </div>
    <span class="pct-raw">${fmtVal}</span>
  </div>`;
}

function playerKey(name, team) {
  return `${team}::${name}`;
}

function renderGameLogTable(title, rows, cols) {
  if (!rows || !rows.length) return '';
  return `<div class="game-log-section">
    <div class="game-log-title">${title}</div>
    <div class="lb-table-wrap game-log-table-wrap">
      <table>
        <thead><tr>${cols.map(c => `<th class="${c.num ? 'num' : ''}">${c.label}</th>`).join('')}</tr></thead>
        <tbody>${rows.map(r => `<tr>${cols.map(c => `<td class="${c.num ? 'num' : ''}">${r[c.key] ?? '—'}</td>`).join('')}</tr>`).join('')}</tbody>
      </table>
    </div>
  </div>`;
}

function renderPlayerGameLogs(name, team) {
  const logs = (typeof PLAYER_LOGS !== 'undefined' ? PLAYER_LOGS[playerKey(name, team)] : null) || {};
  const hitCols = [
    {key:'date', label:'Date'}, {key:'opp', label:'Opponent'}, {key:'res', label:'Result'},
    {key:'AB', label:'AB', num:true}, {key:'R', label:'R', num:true}, {key:'H', label:'H', num:true},
    {key:'RBI', label:'RBI', num:true}, {key:'B1', label:'1B', num:true}, {key:'B2', label:'2B', num:true},
    {key:'B3', label:'3B', num:true}, {key:'HR', label:'HR', num:true}, {key:'BB', label:'BB', num:true},
    {key:'HBP', label:'HBP', num:true}, {key:'SB', label:'SB', num:true}, {key:'AVG', label:'AVG', num:true},
    {key:'SLG', label:'SLG', num:true},
  ];
  const pitCols = [
    {key:'date', label:'Date'}, {key:'opp', label:'Opponent'}, {key:'res', label:'Result'},
    {key:'W', label:'W', num:true}, {key:'L', label:'L', num:true}, {key:'PIT', label:'PIT', num:true},
    {key:'IP', label:'IP', num:true}, {key:'H', label:'H', num:true}, {key:'R', label:'R', num:true},
    {key:'ER', label:'ER', num:true}, {key:'BB', label:'BB', num:true}, {key:'K', label:'K', num:true},
    {key:'HB', label:'HBP', num:true}, {key:'ERA', label:'ERA', num:true},
  ];
  const html = [
    renderGameLogTable('Hitting Game Log', logs.hitting, hitCols),
    renderGameLogTable('Pitching Game Log', logs.pitching, pitCols),
  ].filter(Boolean).join('');
  return html || `<div class="game-log-section"><div class="game-log-empty">No game log is available for this player yet.</div></div>`;
}

function ensurePlayerLogsLoaded() {
  if (typeof PLAYER_LOGS !== 'undefined') return Promise.resolve();
  if (playerLogsLoadPromise) return playerLogsLoadPromise;
  playerLogsLoadPromise = new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = 'js/player_logs.js';
    script.onload = resolve;
    script.onerror = reject;
    document.body.appendChild(script);
  });
  return playerLogsLoadPromise;
}

function loadPlayerGameLogs(name, team) {
  const el = document.getElementById('playerGameLogs');
  if (!el) return;
  ensurePlayerLogsLoaded()
    .then(() => {
      const current = document.getElementById('playerGameLogs');
      if (current) current.innerHTML = renderPlayerGameLogs(name, team);
    })
    .catch(() => {
      const current = document.getElementById('playerGameLogs');
      if (current) current.innerHTML = `<div class="game-log-section"><div class="game-log-empty">Game log could not be loaded.</div></div>`;
    });
}

function showLastUpdated() {
  // Pull last-updated comment from data.js via AP array timestamp if available
  const el1 = document.getElementById('hitLastUpdated');
  const el2 = document.getElementById('pitLastUpdated');
  if (typeof DATA_UPDATED !== 'undefined') {
    const txt = `Updated ${DATA_UPDATED}`;
    if (el1) el1.textContent = txt;
    if (el2) el2.textContent = txt;
  }
}

// ── POPULATE TEAM FILTER DROPDOWNS ────────────────────────────────────────────
function buildTeamFilters() {
  ['hitTeamFilter','pitTeamFilter'].forEach(id => {
    const sel = document.getElementById(id);
    if (!sel || sel.options.length > 1) return;
    const confs = [...new Set(Object.values(TM).map(m => m.div).filter(Boolean))].sort();
    confs.forEach(conf => {
      const teams = Object.keys(TM).filter(t => TM[t].div === conf).sort();
      const grp = document.createElement('optgroup');
      grp.label = conf;
      teams.forEach(t => {
        const o = document.createElement('option');
        o.value = t; o.textContent = t;
        grp.appendChild(o);
      });
      sel.appendChild(grp);
    });
  });
}

// ── HITTING LEADERBOARD ────────────────────────────────────────────────────────
function renderHitTable() {
  const isStd = hitMode === 'standard';
  const ss    = document.getElementById('hitStatFilter').value;
  const tf    = document.getElementById('hitTeamFilter').value;
  const gf    = document.getElementById('hitGradeFilter').value;
  const minPA = parseInt(document.getElementById('hitMinPA').value) || 0;
  const q     = document.getElementById('hitSearchInput').value.trim().toLowerCase();

  // Update tab UI
  document.getElementById('hitTabStd')?.classList.toggle('lb-tab-active', isStd);
  document.getElementById('hitTabAdv')?.classList.toggle('lb-tab-active', !isStd);
  // Show/hide stat filter (only relevant for advanced)
  const sf = document.getElementById('hitStatFilterWrap');
  if (sf) sf.style.display = isStd ? 'none' : '';

  const qualP = AP.filter(p => p.qualified);
  const pf    = {};
  HIT_TABLE_COLS.forEach(s => {
    const vs = qualP.map(p => p[s]);
    pf[s] = v => calcPct(vs, v, false);
  });

  const selDivs = getSelectedDivs('hitDiv');
  let pl = AP;
  if (selDivs) pl = pl.filter(p => selDivs.includes(TM[p.team]?.div));
  if (tf !== 'all') pl = pl.filter(p => p.team === tf);
  if (gf !== 'all') pl = pl.filter(p => p.year === gf);
  if (q) pl = pl.filter(p => p.name.toLowerCase().includes(q));
  pl = pl.filter(p => p.PA >= minPA);

  if (isStd) {
    pl = [...pl].sort((a, b) => hitStdSort.asc
      ? (a[hitStdSort.col] ?? 0) - (b[hitStdSort.col] ?? 0)
      : (b[hitStdSort.col] ?? 0) - (a[hitStdSort.col] ?? 0));
  } else {
    pl = [...pl].sort((a, b) => b[ss] - a[ss]);
  }

  document.getElementById('hitResultsInfo').innerHTML =
    `Showing <span>${pl.length}</span> player${pl.length !== 1 ? 's' : ''}`;

  const hitPages = Math.max(1, Math.ceil(pl.length / LEADER_PAGE_SIZE));
  hitPage = Math.min(Math.max(hitPage, 1), hitPages);
  const pageStart = (hitPage - 1) * LEADER_PAGE_SIZE;
  const pagePlayers = pl.slice(pageStart, pageStart + LEADER_PAGE_SIZE);
  renderPagination('hit', pl.length, hitPage, LEADER_PAGE_SIZE);

  if (isStd) {
    const arrow = hitStdSort.asc ? ' ▴' : ' ▾';
    document.getElementById('hitLbHead').innerHTML =
      `<tr>
        <th style="width:36px">#</th><th>Player</th><th>Team</th>
        <th class="num" onclick="setHitStdSort('PA')" style="cursor:pointer" ${hitStdSort.col==='PA'?'class="num sorted"':''}>PA${hitStdSort.col==='PA'?arrow:''}</th>
        ${HIT_STD_COLS.map(s => {
          const isSorted = hitStdSort.col === s;
          return `<th class="num${isSorted?' sorted':''}" onclick="setHitStdSort('${s}')" style="cursor:pointer" ${HIT_STD_CFG[s]?.tip?`data-tip="${HIT_STD_CFG[s].tip}"`:''}>${HIT_STD_CFG[s]?.label||s}${isSorted?arrow:''}</th>`;
        }).join('')}
      </tr>`;
    if (!pl.length) { document.getElementById('hitLbBody').innerHTML = `<tr><td colspan="20" class="empty">No players match your filters.</td></tr>`; return; }
    document.getElementById('hitLbBody').innerHTML = pagePlayers.map((p, i) => {
      const r = pageStart + i + 1;
      const cells = HIT_STD_COLS.map(s => {
        const v = p[s] ?? 0;
        const isSorted = hitStdSort.col === s;
        return `<td class="num" style="color:var(--muted2);font-weight:${isSorted?'700':'400'}">${HIT_STD_CFG[s]?.fmt(v) ?? v}</td>`;
      }).join('');
      return `<tr onclick="showPlayer('${encodeURIComponent(p.name)}','${p.team}','leaderboard')">
        <td class="rank-cell${r<=3?' top3':''}">${r}</td>${playerCell(p)}<td>${chip(p.team)}</td><td class="num">${p.PA}</td>${cells}</tr>`;
    }).join('');
  } else {
    document.getElementById('hitLbHead').innerHTML =
      `<tr>
        <th style="width:36px">#</th><th>Player</th><th>Team</th><th class="num">PA</th>
        ${HIT_TABLE_COLS.map(s =>
          `<th class="num${s===ss?' sorted':''}" ${HIT_TIPS[s]?`data-tip="${HIT_TIPS[s]}"`:''}>
            ${HSC[s].label}${s===ss?' ▾':''}
          </th>`).join('')}
      </tr>`;
    if (!pl.length) { document.getElementById('hitLbBody').innerHTML = `<tr><td colspan="20" class="empty">No players match your filters.</td></tr>`; return; }
    document.getElementById('hitLbBody').innerHTML = pagePlayers.map((p, i) => {
      const r = pageStart + i + 1;
      const cells = HIT_TABLE_COLS.map(s => {
        const v = p[s], pt = pf[s](v), clr = pc(pt), f = HSC[s].fmt(v), isSorted = s === ss;
        return `<td class="num" style="color:${clr};font-weight:${isSorted?'700':'500'}">${f}</td>`;
      }).join('');
      return `<tr onclick="showPlayer('${encodeURIComponent(p.name)}','${p.team}','leaderboard')">
        <td class="rank-cell${r<=3?' top3':''}">${r}</td>${playerCell(p)}<td>${chip(p.team)}</td><td class="num">${p.PA}</td>${cells}</tr>`;
    }).join('');
  }
}

// ── PITCHING LEADERBOARD ───────────────────────────────────────────────────────
function renderPitchTable() {
  const isStd = pitMode === 'standard';
  const ss    = document.getElementById('pitStatFilter').value;
  const tf    = document.getElementById('pitTeamFilter').value;
  const gf    = document.getElementById('pitGradeFilter').value;
  const minIP = parseFloat(document.getElementById('pitMinIP').value) || 0;
  const q     = document.getElementById('pitSearchInput').value.trim().toLowerCase();

  document.getElementById('pitTabStd')?.classList.toggle('lb-tab-active', isStd);
  document.getElementById('pitTabAdv')?.classList.toggle('lb-tab-active', !isStd);
  const sf = document.getElementById('pitStatFilterWrap');
  if (sf) sf.style.display = isStd ? 'none' : '';

  const qualP = PP.filter(p => p.qualPitch);
  const pf    = {};
  PIT_TABLE_COLS.forEach(s => {
    const vs = qualP.map(p => p[s]).filter(v => isFinite(v));
    pf[s] = v => calcPct(vs, v, PSC[s].lowerBetter);
  });

  const lb = PSC[ss] && PSC[ss].lowerBetter;
  const selDivs = getSelectedDivs('pitDiv');
  let pl = PP;
  if (selDivs) pl = pl.filter(p => selDivs.includes(TM[p.team]?.div));
  if (tf !== 'all') pl = pl.filter(p => p.team === tf);
  if (gf !== 'all') pl = pl.filter(p => p.year === gf);
  if (q) pl = pl.filter(p => p.name.toLowerCase().includes(q));
  pl = pl.filter(p => p.IP >= minIP);

  if (isStd) {
    pl = [...pl].sort((a, b) => pitStdSort.asc
      ? (a[pitStdSort.col] ?? 0) - (b[pitStdSort.col] ?? 0)
      : (b[pitStdSort.col] ?? 0) - (a[pitStdSort.col] ?? 0));
  } else {
    pl = [...pl].sort((a, b) => lb ? a[ss] - b[ss] : b[ss] - a[ss]);
  }

  document.getElementById('pitResultsInfo').innerHTML =
    `Showing <span>${pl.length}</span> pitcher${pl.length !== 1 ? 's' : ''}`;

  const pitPages = Math.max(1, Math.ceil(pl.length / LEADER_PAGE_SIZE));
  pitPage = Math.min(Math.max(pitPage, 1), pitPages);
  const pageStart = (pitPage - 1) * LEADER_PAGE_SIZE;
  const pagePitchers = pl.slice(pageStart, pageStart + LEADER_PAGE_SIZE);
  renderPagination('pit', pl.length, pitPage, LEADER_PAGE_SIZE);

  if (isStd) {
    const arrow = pitStdSort.asc ? ' ▴' : ' ▾';
    document.getElementById('pitLbHead').innerHTML =
      `<tr>
        <th style="width:36px">#</th><th>Pitcher</th><th>Team</th>
        ${PIT_STD_COLS.map(s => {
          const isSorted = pitStdSort.col === s;
          return `<th class="num${isSorted?' sorted':''}" onclick="setPitStdSort('${s}')" style="cursor:pointer" ${PIT_STD_CFG[s]?.tip?`data-tip="${PIT_STD_CFG[s].tip}"`:''}>${PIT_STD_CFG[s]?.label||s}${isSorted?arrow:''}</th>`;
        }).join('')}
      </tr>`;
    if (!pl.length) { document.getElementById('pitLbBody').innerHTML = `<tr><td colspan="20" class="empty">No pitchers match your filters.</td></tr>`; return; }
    document.getElementById('pitLbBody').innerHTML = pagePitchers.map((p, i) => {
      const r = pageStart + i + 1;
      const opacity = p.IP < 15 ? 'opacity:0.45' : '';
      const cells = PIT_STD_COLS.map(s => {
        const v = p[s] ?? 0;
        const isSorted = pitStdSort.col === s;
        return `<td class="num" style="color:var(--muted2);font-weight:${isSorted?'700':'400'}">${isFinite(v) ? (PIT_STD_CFG[s]?.fmt(v) ?? v) : '—'}</td>`;
      }).join('');
      return `<tr style="${opacity}" onclick="showPlayer('${encodeURIComponent(p.name)}','${p.team}','pitching')">
        <td class="rank-cell${r<=3?' top3':''}">${r}</td>${playerCell(p)}<td>${chip(p.team)}</td>${cells}</tr>`;
    }).join('');
  } else {
    document.getElementById('pitLbHead').innerHTML =
      `<tr>
        <th style="width:36px">#</th><th>Pitcher</th><th>Team</th><th class="num">IP</th><th class="num">W</th><th class="num">L</th>
        ${PIT_TABLE_COLS.map(s =>
          `<th class="num${s===ss?' sorted':''}" ${PIT_TIPS[s]?`data-tip="${PIT_TIPS[s]}"`:''}>
            ${PSC[s].label}${s===ss?(lb?' ▴':' ▾'):''}
          </th>`).join('')}
      </tr>`;
    if (!pl.length) { document.getElementById('pitLbBody').innerHTML = `<tr><td colspan="20" class="empty">No pitchers match your filters.</td></tr>`; return; }
    document.getElementById('pitLbBody').innerHTML = pagePitchers.map((p, i) => {
      const r = pageStart + i + 1;
      const opacity = p.IP < 15 ? 'opacity:0.45' : '';
      const cells = PIT_TABLE_COLS.map(s => {
        const v = p[s];
        if (!isFinite(v)) return `<td class="num" style="color:var(--muted)">—</td>`;
        const pt = pf[s](v), clr = pc(pt), f = PSC[s].fmt(v), isSorted = s === ss;
        return `<td class="num" style="color:${clr};font-weight:${isSorted?'700':'500'}">${f}</td>`;
      }).join('');
      return `<tr style="${opacity}" onclick="showPlayer('${encodeURIComponent(p.name)}','${p.team}','pitching')">
        <td class="rank-cell${r<=3?' top3':''}">${r}</td>${playerCell(p)}<td>${chip(p.team)}</td>
        <td class="num">${p.IP.toFixed(1)}</td><td class="num">${p.W}</td><td class="num">${p.L}</td>${cells}</tr>`;
    }).join('');
  }
}

// ── PLAYER PAGE ────────────────────────────────────────────────────────────────
function showPlayer(enc, team, from) {
  const name    = decodeURIComponent(enc);
  prevView      = from || 'leaderboard';
  const hitter  = AP.find(p => p.name === name && p.team === team);
  const pitcher = PP.find(p => p.name === name && p.team === team);
  if (!hitter && !pitcher) return;

  const m          = TM[team] || { p:'#222', s:'#444', t:'#aaa', bg:'#111', mascot:'', svg:'' };
  const playerName = hitter ? hitter.name : pitcher.name;
  const playerPos  = hitter ? hitter.pos  : (pitcher ? pitcher.pos  : '');
  const playerYear = hitter ? hitter.year : (pitcher ? pitcher.year : '');
  const isTwoWay   = hitter && pitcher;

  // Hitting panel
  let hitPanel = '';
  if (hitter) {
    const qualP    = AP.filter(p => p.qualified);
    const allStats = ['AVG','SLG','OBP','OPS','BsR','ISO','BB_pct','wOBA','wRAA','wRC','wRC_plus'];
    const hpf      = {};
    allStats.forEach(s => {
      const vs = qualP.map(p => p[s]).filter(v => isFinite(v));
      hpf[s] = v => calcPct(vs, v, false);
    });
    const miniCards = [['PS','PS'],['AVG','AVG'],['OPS','OPS'],['wRC+','wRC_plus'],['wOBA','wOBA']].map(([l, k]) =>
      `<div class="stat-mini">
        <div class="stat-mini-label">${l}</div>
        <div class="stat-mini-val">${HSC[k].fmt(hitter[k])}</div>
      </div>`
    ).join('');
    const sects = HIT_PCT_GROUPS.map(g =>
      `<div class="pct-section">
        <div class="pct-section-title">${g.title}</div>
        ${g.stats.map(s => {
          const v = hitter[s], pt = hpf[s](v), f = HSC[s].fmt(v);
          return pctRow(HSC[s].label, v, pt, f);
        }).join('')}
      </div>`
    ).join('');
    const paTag   = `<span class="p-tag pa">${hitter.PA} PA</span>`;
    const nonqTag = !hitter.qualified ? `<span class="p-tag nonq">Non-Qualified</span>` : '';
    hitPanel = `<div class="stat-mini-grid">${miniCards}</div>${sects}`;
    if (!isTwoWay) hitPanel = `<div style="margin-bottom:10px;display:flex;gap:6px;flex-wrap:wrap">${paTag}${nonqTag}</div>` + hitPanel;
  }

  // Pitching panel
  let pitPanel = '';
  if (pitcher) {
    const qualP    = PP.filter(p => p.qualPitch);
    const allStats = Object.keys(PSC);
    const ppf      = {};
    allStats.forEach(s => {
      const vs = qualP.map(p => p[s]).filter(v => isFinite(v));
      ppf[s] = v => calcPct(vs, v, PSC[s].lowerBetter);
    });
    const miniCards = [['PS','PS'],['ERA','ERA'],['FIP','FIP'],['WHIP','WHIP'],['K/7','K7']].map(([l, k]) => {
      const v = pitcher[k];
      return `<div class="stat-mini">
        <div class="stat-mini-label">${l}</div>
        <div class="stat-mini-val">${isFinite(v) ? PSC[k].fmt(v) : '—'}</div>
      </div>`;
    }).join('');
    const sects = PIT_PCT_GROUPS.map(g =>
      `<div class="pct-section">
        <div class="pct-section-title">${g.title}</div>
        ${g.stats.map(s => {
          const v = pitcher[s];
          if (!isFinite(v)) return `<div class="pct-row"><span class="pct-label">${PSC[s].label}</span><span style="color:var(--muted);font-size:13px">—</span></div>`;
          const pt = ppf[s](v), f = PSC[s].fmt(v);
          return pctRow(PSC[s].label, v, pt, f);
        }).join('')}
      </div>`
    ).join('');
    const ipTag   = `<span class="p-tag pa">${pitcher.IP.toFixed(1)} IP · ${pitcher.W}W-${pitcher.L}L</span>`;
    const nonqTag = !pitcher.qualPitch ? `<span class="p-tag nonq">Non-Qualified (&lt;15 IP)</span>` : '';
    pitPanel = `<div style="margin-bottom:10px;display:flex;gap:6px;flex-wrap:wrap">${ipTag}${nonqTag}</div>
      <div class="stat-mini-grid">${miniCards}</div>${sects}`;
  }

  // Two-way tabs
  let bodyHTML = '';
  if (isTwoWay) {
    const paTag   = `<span class="p-tag pa">${hitter.PA} PA</span>`;
    const nonqHit = !hitter.qualified ? `<span class="p-tag nonq">Non-Qualified</span>` : '';
    const encName = encodeURIComponent(name);
    bodyHTML = `
      <div style="display:flex;gap:6px;flex-wrap:wrap;margin-bottom:1rem">${paTag}${nonqHit}</div>
      <div class="role-tabs">
        <button class="role-tab active" onclick="switchRole(this,'hit-panel-${encName}')">Hitting</button>
        <button class="role-tab" onclick="switchRole(this,'pit-panel-${encName}')">Pitching</button>
      </div>
      <div id="hit-panel-${encName}" class="role-panel active">${hitPanel}</div>
      <div id="pit-panel-${encName}" class="role-panel">${pitPanel}</div>`;
  } else if (hitter) {
    bodyHTML = hitPanel;
  } else {
    bodyHTML = pitPanel;
  }

  document.getElementById('playerContent').innerHTML = `
    <div class="player-hero">
      <div class="player-shield" style="background:${m.bg};border:1px solid ${m.s}55">
        ${m.logo ? `<img src="${m.logo}" width="48" height="48" style="object-fit:contain;border-radius:4px">` : ''}
      </div>
      <div class="player-info">
        <div class="player-full-name">${playerName}</div>
        <div class="player-details">
          <span class="p-tag" style="background:${m.bg};color:${m.t};border-color:${m.s}55;display:inline-flex;align-items:center;gap:5px;cursor:pointer"
            onclick="showTeam('${team}','player')">
            ${teamLogo(team, 12)}
            ${team} <span style="opacity:.5;font-weight:400;margin-left:2px">${m.mascot}</span>
          </span>
          ${playerYear ? `<span class="p-tag">${playerYear}</span>` : ''}
          ${playerPos  ? `<span class="p-tag">${playerPos}</span>`  : ''}
          ${isTwoWay   ? `<span class="p-tag" style="color:var(--accent);border-color:rgba(232,200,74,0.35);background:var(--accent2)">Two-Way</span>` : ''}
        </div>
      </div>
    </div>
    ${bodyHTML}
    <div id="playerGameLogs">
      <div class="game-log-section"><div class="game-log-empty">Loading game log...</div></div>
    </div>`;

  showView('player', from);
  loadPlayerGameLogs(playerName, team);
}

function switchRole(btn, panelId) {
  const wrap = btn.closest('.player-wrap');
  wrap.querySelectorAll('.role-tab').forEach(t => t.classList.remove('active'));
  wrap.querySelectorAll('.role-panel').forEach(p => p.classList.remove('active'));
  btn.classList.add('active');
  document.getElementById(panelId).classList.add('active');
}

// ── TEAMS NAV (dynamic) ────────────────────────────────────────────────────────
function buildTeamsNav() {
  const el = document.getElementById('teamsNavList');
  if (!el) return;
  const confs = [...new Set(Object.values(TM).map(m => m.div).filter(Boolean))].sort();
  el.innerHTML = confs.map(conf => {
    const teams = Object.keys(TM).filter(t => TM[t].div === conf);
    return `<div class="nav-dropdown-label">${conf}</div>` +
      teams.map(t => `<button class="nav-dropdown-item" onclick="showTeam('${t}','nav');closeDropdowns()">${t}</button>`).join('');
  }).join('<div class="nav-dropdown-divider"></div>');
}

// ── TEAMS OVERVIEW ─────────────────────────────────────────────────────────────
function renderTeamsGrid() {
  // Populate conference filter on first run
  const sel = document.getElementById('teamsConfFilter');
  if (sel && sel.options.length === 1) {
    const confs = [...new Set(Object.values(TM).map(m => m.div).filter(Boolean))].sort();
    confs.forEach(c => {
      const o = document.createElement('option');
      o.value = c; o.textContent = c;
      sel.appendChild(o);
    });
  }
  const confFilter = sel?.value || 'all';
  const q = document.getElementById('teamsSearchInput')?.value.trim().toLowerCase() || '';

  let teams = Object.keys(TM);
  if (confFilter !== 'all') teams = teams.filter(t => TM[t].div === confFilter);
  if (q) teams = teams.filter(t => t.toLowerCase().includes(q) || (TM[t].mascot||'').toLowerCase().includes(q));

  document.getElementById('teamsGrid').innerHTML = teams.map(team => {
    const m      = TM[team];
    const qp     = AP.filter(p => p.team === team && p.qualified);
    const allP   = AP.filter(p => p.team === team);
    const avgAVG = qp.length ? qp.reduce((s, p) => s + p.AVG, 0) / qp.length : 0;
    const avgOPS = qp.length ? qp.reduce((s, p) => s + p.OPS, 0) / qp.length : 0;
    const tPA    = allP.reduce((s, p) => s + p.PA, 0);
    const tWOBA  = tPA > 0
      ? (0.7*(allP.reduce((s,p)=>s+p.BB+p.HBP,0)) + 0.9*(allP.reduce((s,p)=>s+p.B1,0)) + 1.3*(allP.reduce((s,p)=>s+p.B2,0)) + 1.6*(allP.reduce((s,p)=>s+p.B3,0)) + 2*(allP.reduce((s,p)=>s+p.HR,0))) / tPA
      : 0;
    const avgWRC = Math.round(((tWOBA - 0.353) / 1.12 + 0.177) / 0.177 * 100);
    return `<div class="team-card" onclick="showTeam('${team}','teams')" style="border-color:${m.s}44">
      <div class="team-card-header">
        <div class="team-card-icon" style="background:${m.bg};border:1px solid ${m.s}55">
          ${m.logo ? `<img src="${m.logo}" width="30" height="30" style="object-fit:contain">` : ''}
        </div>
        <div>
          <div class="team-card-name" style="color:${m.t}">${team}</div>
          <div class="team-card-mascot" style="color:${m.s}">${m.mascot}</div>
        </div>
      </div>
      <div class="team-card-stats">
        <div class="team-card-stat">
          <div class="team-card-stat-val" style="color:${m.t}">${avgAVG.toFixed(3).replace(/^0/,'')}</div>
          <div class="team-card-stat-label">Avg AVG</div>
        </div>
        <div class="team-card-stat">
          <div class="team-card-stat-val" style="color:${m.t}">${avgOPS.toFixed(3)}</div>
          <div class="team-card-stat-label">Avg OPS</div>
        </div>
        <div class="team-card-stat">
          <div class="team-card-stat-val" style="color:${m.t}">${avgWRC}</div>
          <div class="team-card-stat-label">Avg wRC+</div>
        </div>
      </div>
    </div>`;
  }).join('');
}

// ── TEAM PAGE ──────────────────────────────────────────────────────────────────
function showTeam(team, from) {
  prevView = from || 'teams';
  const m  = TM[team] || { p:'#222', s:'#444', t:'#aaa', bg:'#111', mascot:'', svg:'' };
  const tp = AP.filter(p => p.team === team);
  const qp = tp.filter(p => p.qualified);

  const wavg = (arr, k) => {
    const tot = arr.reduce((s, p) => s + p.PA, 0);
    return tot ? arr.reduce((s, p) => s + p[k] * p.PA, 0) / tot : 0;
  };

  const teamAVG  = wavg(tp, 'AVG');
  const teamOBP  = wavg(tp, 'OBP');
  const teamSLG  = wavg(tp, 'SLG');
  const teamPA   = tp.reduce((s, p) => s + p.PA, 0);
  const teamwOBA = teamPA > 0
    ? (0.7*(tp.reduce((s,p)=>s+p.BB+p.HBP,0)) + 0.9*(tp.reduce((s,p)=>s+p.B1,0)) + 1.3*(tp.reduce((s,p)=>s+p.B2,0)) + 1.6*(tp.reduce((s,p)=>s+p.B3,0)) + 2*(tp.reduce((s,p)=>s+p.HR,0))) / teamPA
    : 0;
  const teamwRCplus = Math.round(((teamwOBA - 0.353) / 1.12 + 0.177) / 0.177 * 100);
  const teamOPS     = teamOBP + teamSLG;
  const pitchers    = PP.filter(p => p.team === team);
  const teamERA     = pitchers.reduce((s, p) => s + p.ER, 0) / (pitchers.reduce((s, p) => s + p.IP, 0) / 7) || 0;
  const teamWHIP    = pitchers.reduce((s, p) => s + p.BB + p.H, 0) / pitchers.reduce((s, p) => s + p.IP, 0) || 0;

  const hitCols = ['PA','AVG','OBP','SLG','OPS','ISO','wOBA','wRC_plus','PS'];
  const pitCols = ['IP','W','L','ERA','FIP','WHIP','K7','BB7','KBB','PS'];

  const hitRows = [...tp].sort((a, b) => b.PA - a.PA).map(p =>
    `<tr onclick="showPlayer('${encodeURIComponent(p.name)}','${p.team}','team-${team}')"
      style="${!p.qualified ? 'opacity:0.45' : ''}">
      ${playerCell(p)}
      <td><span class="p-tag" style="font-size:10px;padding:2px 7px;
        background:${p.qualified ? 'var(--accent2)' : 'var(--surface2)'};
        color:${p.qualified ? 'var(--accent)' : 'var(--muted2)'};
        border-color:${p.qualified ? 'rgba(232,200,74,0.3)' : 'var(--border2)'}">${p.PA} PA</span></td>
      ${hitCols.slice(1).map(s => `<td class="num" style="font-size:12px">${HSC[s] ? HSC[s].fmt(p[s]) : p[s]}</td>`).join('')}
    </tr>`
  ).join('');

  const pitRows = [...pitchers].sort((a, b) => b.IP - a.IP).map(p =>
    `<tr onclick="showPlayer('${encodeURIComponent(p.name)}','${p.team}','team-${team}')"
      style="${!p.qualPitch ? 'opacity:0.45' : ''}">
      ${playerCell(p)}
      <td class="num" style="font-size:12px">${p.IP.toFixed(1)}</td>
      <td class="num" style="font-size:12px">${p.W}-${p.L}</td>
      ${pitCols.slice(3).map(s => `<td class="num" style="font-size:12px">${isFinite(p[s]) ? PSC[s].fmt(p[s]) : '—'}</td>`).join('')}
    </tr>`
  ).join('');

  const sched   = (typeof SCHEDULES !== 'undefined' && SCHEDULES[team]) || {};
  const coach   = sched.coach  || '';
  const wins    = sched.wins   ?? '';
  const losses  = sched.losses ?? '';
  const games   = sched.games  || [];
  const record  = (wins !== '' && losses !== '') ? `${wins}-${losses}` : '';

  const gameRows = games.map(g => {
    const loc     = g.home ? 'vs' : '@';
    const wl      = g.outcome === 'W' ? `<span style="color:#4ade80;font-weight:700">W</span>` :
                    g.outcome === 'L' ? `<span style="color:#f87171;font-weight:700">L</span>` : '—';
    return `<tr>
      <td style="color:var(--muted2);font-size:12px;white-space:nowrap">${g.date}</td>
      <td style="font-size:13px"><span style="color:var(--muted);font-size:11px;margin-right:4px">${loc}</span>${g.opponent}</td>
      <td class="num" style="font-size:13px">${wl}</td>
      <td class="num" style="font-size:13px;font-variant-numeric:tabular-nums">${g.score || '—'}</td>
    </tr>`;
  }).join('');

  document.getElementById('teamContent').innerHTML = `
    <div class="team-hero">
      <div class="team-shield-lg" style="background:${m.bg};border:1px solid ${m.s}55">
        ${m.logo ? `<img src="${m.logo}" width="52" height="52" style="object-fit:contain">` : ''}
      </div>
      <div style="flex:1">
        <div class="team-name-lg" style="color:${m.t}">${team}</div>
        <div class="team-mascot-lg" style="color:${m.s};margin-bottom:10px">${m.mascot}</div>
        <div style="display:flex;gap:20px;flex-wrap:wrap;align-items:center">
          ${record ? `<div>
            <span style="font-family:'Bebas Neue',sans-serif;font-size:11px;letter-spacing:.1em;color:var(--muted)">RECORD&nbsp;&nbsp;</span>
            <span style="font-family:'Bebas Neue',sans-serif;font-size:20px;letter-spacing:.04em;color:var(--accent)">${record}</span>
          </div>` : ''}
          ${coach ? `<div>
            <span style="font-family:'Bebas Neue',sans-serif;font-size:11px;letter-spacing:.1em;color:var(--muted)">HEAD COACH&nbsp;&nbsp;</span>
            <span style="font-family:'Inter',sans-serif;font-size:14px;font-weight:600;color:var(--text)">${coach}</span>
          </div>` : ''}
          <div>
            <span style="font-family:'Bebas Neue',sans-serif;font-size:11px;letter-spacing:.1em;color:var(--muted)">DIVISION&nbsp;&nbsp;</span>
            <span style="font-family:'Inter',sans-serif;font-size:14px;font-weight:600;color:var(--text)">${m.div || ''}</span>
          </div>
        </div>
      </div>
    </div>
    <div class="team-stat-cards">
      <div class="team-stat-card"><div class="team-stat-card-label">AVG</div><div class="team-stat-card-val" style="color:${m.t}">${teamAVG.toFixed(3).replace(/^0/,'')}</div></div>
      <div class="team-stat-card"><div class="team-stat-card-label">OPS</div><div class="team-stat-card-val" style="color:${m.t}">${teamOPS.toFixed(3)}</div></div>
      <div class="team-stat-card"><div class="team-stat-card-label">wOBA</div><div class="team-stat-card-val" style="color:${m.t}">${teamwOBA.toFixed(3).replace(/^0/,'')}</div></div>
      <div class="team-stat-card"><div class="team-stat-card-label">wRC+</div><div class="team-stat-card-val" style="color:${m.t}">${teamwRCplus}</div></div>
      <div class="team-stat-card"><div class="team-stat-card-label">ERA</div><div class="team-stat-card-val" style="color:${m.t}">${teamERA.toFixed(2)}</div></div>
      <div class="team-stat-card"><div class="team-stat-card-label">WHIP</div><div class="team-stat-card-val" style="color:${m.t}">${teamWHIP.toFixed(2)}</div></div>
    </div>
    <div class="team-section-tabs">
      <button class="team-section-tab active" onclick="switchTeamPanel(this,'tp-hit-${team}')">Hitting Roster</button>
      <button class="team-section-tab" onclick="switchTeamPanel(this,'tp-pit-${team}')">Pitching Roster</button>
      <button class="team-section-tab" onclick="switchTeamPanel(this,'tp-sched-${team}')">Schedule</button>
    </div>
    <div id="tp-hit-${team}" class="team-panel active">
      <div class="lb-table-wrap"><table>
        <thead><tr><th>Player</th><th>PA</th>${hitCols.slice(1).map(s => `<th class="num">${HSC[s] ? HSC[s].label : s}</th>`).join('')}</tr></thead>
        <tbody>${hitRows}</tbody>
      </table></div>
    </div>
    <div id="tp-pit-${team}" class="team-panel">
      <div class="lb-table-wrap"><table>
        <thead><tr><th>Pitcher</th><th class="num">IP</th><th class="num">W-L</th>${pitCols.slice(3).map(s => `<th class="num">${PSC[s].label}</th>`).join('')}</tr></thead>
        <tbody>${pitRows}</tbody>
      </table></div>
    </div>
    <div id="tp-sched-${team}" class="team-panel">
      ${gameRows ? `<div class="lb-table-wrap"><table>
        <thead><tr>
          <th>Date</th>
          <th>Opponent</th>
          <th class="num">W/L</th>
          <th class="num">Score</th>
        </tr></thead>
        <tbody>${gameRows}</tbody>
      </table></div>` : '<div class="empty">No schedule data available.</div>'}
    </div>`;

  showView('team', from);
}

function switchTeamPanel(btn, panelId) {
  const wrap = btn.closest('.team-wrap');
  wrap.querySelectorAll('.team-section-tab').forEach(t => t.classList.remove('active'));
  wrap.querySelectorAll('.team-panel').forEach(p => p.classList.remove('active'));
  btn.classList.add('active');
  document.getElementById(panelId).classList.add('active');
}

// ── VIEW MANAGEMENT ────────────────────────────────────────────────────────────
function showView(v, from) {
  document.querySelectorAll('.view').forEach(x => x.classList.remove('active'));
  document.getElementById('view-' + v).classList.add('active');
  const back = document.getElementById('backBtn');
  const nav  = document.getElementById('navTabs');

  if (v === 'player' || v === 'team') {
    back.style.display = 'flex';
    nav.style.display  = 'flex';
    let lbl = 'Back';
    if (from === 'home')                       lbl = 'Home';
    else if (from === 'leaderboard')           lbl = 'Hitting';
    else if (from === 'pitching')              lbl = 'Pitching';
    else if (from === 'teams')                 lbl = 'Teams';
    else if (from === 'team-rankings')         lbl = 'Rankings';
    else if (from === 'nav')                   lbl = 'Back';
    else if (from && from.startsWith('team-')) lbl = from.replace('team-', '');
    document.getElementById('backLabel').textContent = lbl;
  } else {
    back.style.display = 'none';
    nav.style.display  = 'flex';
  }
  document.querySelectorAll('.nav-tab').forEach(t => t.classList.remove('active'));
  if (['leaderboard','pitching'].includes(v))       document.getElementById('tab-leaders')?.classList.add('active');
  if (['teams','team','team-rankings'].includes(v)) document.getElementById('tab-teams-dd')?.classList.add('active');
  if (v === 'standings')                            document.getElementById('tab-standings')?.classList.add('active');
  if (v === 'glossary')                             document.getElementById('tab-glossary')?.classList.add('active');
}

function goBack() {
  if (prevView === 'home')                           showView('home');
  else if (prevView === 'teams')                     showView('teams');
  else if (prevView === 'pitching')                  showView('pitching');
  else if (prevView === 'standings')                 showView('standings');
  else if (prevView === 'team-rankings')             showView('team-rankings');
  else if (prevView && prevView.startsWith('team-')) showTeam(prevView.replace('team-', ''), 'teams');
  else                                               showView('leaderboard');
}

// ── CONFERENCE MULTI-SELECT FILTER ────────────────────────────────────────────
function buildDivFilters() {
  const confs = [...new Set(Object.values(TM).map(m => m.div).filter(Boolean))].sort();
  ['hitDiv','pitDiv','rankDiv'].forEach(id => {
    const container = document.getElementById(id + 'Options');
    if (!container || container.children.length > 0) return;
    container.innerHTML = confs.map(c =>
      `<div class="div-filter-option checked" data-div="${c}" onclick="toggleDiv(this,'${id}',event)">
        <div class="div-filter-checkbox"></div>${c}
      </div>`
    ).join('');
  });
}

function getSelectedDivs(id) {
  const container = document.getElementById(id + 'Options');
  if (!container) return null;
  const checked = [...container.querySelectorAll('.div-filter-option.checked')].map(el => el.dataset.div);
  const all     = [...container.querySelectorAll('.div-filter-option')].map(el => el.dataset.div);
  return checked.length === all.length ? null : checked;
}

function toggleDivFilter(id) {
  const menu = document.getElementById(id + 'Menu');
  const isOpen = menu.classList.contains('open');
  // close all other div menus
  document.querySelectorAll('.div-filter-menu').forEach(m => m.classList.remove('open'));
  document.querySelectorAll('.div-filter-btn').forEach(b => b.classList.remove('open'));
  if (!isOpen) menu.classList.add('open');
}

function toggleDiv(el, id, e) {
  el.classList.toggle('checked');
  updateDivFilterBtn(id);
  if (id.startsWith('hit'))  resetHitPage();
  else if (id.startsWith('pit')) resetPitPage();
  else renderTeamRankings();
  if (e) e.stopPropagation();
}

function selectAllDivs(id) {
  const menu = document.getElementById(id + 'Options') || document.getElementById(id + 'Menu');
  menu.querySelectorAll('.div-filter-option').forEach(el => el.classList.add('checked'));
  updateDivFilterBtn(id);
  if (id.startsWith('hit'))  resetHitPage();
  else if (id.startsWith('pit')) resetPitPage();
  else renderTeamRankings();
}

function updateDivFilterBtn(id) {
  const container = document.getElementById(id + 'Options') || document.getElementById(id + 'Menu');
  const btn   = document.getElementById(id + 'Btn');
  if (!container || !btn) return;
  const checked = container.querySelectorAll('.div-filter-option.checked').length;
  const total   = container.querySelectorAll('.div-filter-option').length;
  const isAll   = checked === total;
  btn.classList.toggle('active', !isAll);
  // Update label
  const countEl = btn.querySelector('.div-filter-count');
  if (isAll) {
    if (countEl) countEl.remove();
  } else {
    if (!countEl) {
      const span = document.createElement('span');
      span.className = 'div-filter-count';
      btn.appendChild(span);
    }
    btn.querySelector('.div-filter-count').textContent = checked;
  }
}

// Close div filter menus when clicking outside
document.addEventListener('click', e => {
  if (!e.target.closest('.div-filter-wrap')) {
    document.querySelectorAll('.div-filter-menu').forEach(m => m.classList.remove('open'));
  }
});

// ── DROPDOWN NAV ───────────────────────────────────────────────────────────────
function closeDropdowns() {
  document.querySelectorAll('.nav-dropdown-menu').forEach(m => m.classList.remove('open'));
}

document.addEventListener('click', e => {
  const trigger = e.target.closest('.nav-dropdown-trigger');
  const menu    = e.target.closest('.nav-dropdown-menu');
  if (trigger) {
    const dd = trigger.closest('.nav-dropdown').querySelector('.nav-dropdown-menu');
    const isOpen = dd.classList.contains('open');
    closeDropdowns();
    document.querySelectorAll('.div-filter-menu').forEach(m => m.classList.remove('open'));
    if (!isOpen) dd.classList.add('open');
    e.stopPropagation();
  } else if (!menu) {
    closeDropdowns();
  }
});

// ── HOME PAGE ──────────────────────────────────────────────────────────────────
function renderHome() {

  // Top performers — top 3 hitters by wRC+, top 3 pitchers by strikeouts
  const rankColors  = ['gold','silver','bronze'];
  const qualH       = AP.filter(p => p.qualified);
  const qualP       = PP.filter(p => p.qualPitch);
  const topHitters  = [...qualH].sort((a,b) => b.wRC_plus - a.wRC_plus).slice(0,3);
  const topPitchers = [...qualP].sort((a,b) => b.K - a.K).slice(0,3);

  const perfCard = (p, stat, fmt, label, idx, isPit) => {
    const m = TM[p.team] || {};
    return `<div class="performer-card" onclick="${isPit ? `showPlayer('${encodeURIComponent(p.name)}','${p.team}','home')` : `showPlayer('${encodeURIComponent(p.name)}','${p.team}','home')`}">
      <div class="performer-rank ${rankColors[idx]}">${idx+1}</div>
      <div style="flex-shrink:0">
        ${m.logo ? `<img src="${m.logo}" width="28" height="28" style="object-fit:contain;border-radius:3px">` : ''}
      </div>
      <div class="performer-info">
        <div class="performer-name">${p.name}</div>
        <div class="performer-team">${p.team} · ${p.year || ''} ${p.pos || ''}</div>
      </div>
      <div class="performer-stat">
        <div class="performer-stat-val">${fmt(p[stat])}</div>
        <div class="performer-stat-label">${label}</div>
      </div>
    </div>`;
  };

  document.getElementById('homePerformers').innerHTML =
    `<div style="grid-column:1/-1;font-family:'Outfit',sans-serif;font-size:11px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;color:var(--muted);margin-bottom:4px">Hitting — wRC+</div>`+
    topHitters.map((p,i) => perfCard(p,'wRC_plus',v=>Math.round(v),'wRC+',i,false)).join('')+
    `<div style="grid-column:1/-1;font-family:'Outfit',sans-serif;font-size:11px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;color:var(--muted);margin-top:12px;margin-bottom:4px">Pitching — Strikeouts</div>`+
    topPitchers.map((p,i) => perfCard(p,'K',v=>Math.round(v),'K',i,true)).join('');

  // Articles
  document.getElementById('homeArticles').innerHTML = ARTICLES.map(a => `
    <a class="article-card" href="${a.url}" target="_blank" rel="noopener">
      <div class="article-card-img">${a.emoji}</div>
      <div class="article-card-body">
        <div class="article-card-tag">${a.tag}</div>
        <div class="article-card-title">${a.title}</div>
        <div class="article-card-meta">${a.meta}</div>
      </div>
    </a>`).join('');

  // Team wRC+ rankings preview (top 10)
  const teams = Object.keys(TM).map(team => {
    const tp  = AP.filter(p => p.team === team);
    const tPA = tp.reduce((s,p) => s+p.PA, 0);
    const twOBA = tPA > 0
      ? (0.7*(tp.reduce((s,p)=>s+p.BB+p.HBP,0)) + 0.9*(tp.reduce((s,p)=>s+p.B1,0)) + 1.3*(tp.reduce((s,p)=>s+p.B2,0)) + 1.6*(tp.reduce((s,p)=>s+p.B3,0)) + 2*(tp.reduce((s,p)=>s+p.HR,0))) / tPA
      : 0;
    const twRCplus = Math.round(((twOBA - 0.353) / 1.12 + 0.177) / 0.177 * 100);
    const pitchers = PP.filter(p => p.team === team);
    const tIP  = pitchers.reduce((s,p)=>s+p.IP,0);
    const tERA = tIP > 0 ? (pitchers.reduce((s,p)=>s+p.ER,0) / tIP)*7 : 0;
    const m = TM[team];
    return { team, twRCplus, tERA, m, tPA };
  }).sort((a,b) => b.twRCplus - a.twRCplus);

  document.getElementById('homeTeamRankings').innerHTML =
    `<table class="home-rankings-table">
      <thead><tr>
        <th style="width:28px">#</th>
        <th>Team</th>
        <th class="num">wRC+</th>
        <th class="num">ERA</th>
        <th class="num">PA</th>
      </tr></thead>
      <tbody>
        ${teams.slice(0,10).map((t,i) => `
          <tr onclick="showTeam('${t.team}','home')">
            <td style="font-family:'Outfit',sans-serif;font-weight:700;color:${i<3?'var(--accent)':'var(--muted)'}">${i+1}</td>
            <td>
              <div style="display:flex;align-items:center;gap:8px">
                ${t.m?.logo ? `<img src="${t.m.logo}" width="20" height="20" style="object-fit:contain;border-radius:2px">` : ''}
                <span style="font-family:'Outfit',sans-serif;font-weight:600;color:${t.m?.t||'var(--text)'}">${t.team}</span>
                <span style="font-size:11px;color:var(--muted)">${t.m?.mascot||''}</span>
              </div>
            </td>
            <td class="num" style="font-family:'Outfit',sans-serif;font-weight:700;color:var(--accent)">${t.twRCplus}</td>
            <td class="num" style="color:var(--muted2)">${t.tERA.toFixed(2)}</td>
            <td class="num" style="color:var(--muted2)">${t.tPA}</td>
          </tr>`).join('')}
      </tbody>
    </table>`;
}

// ── TEAM RANKINGS PAGE ─────────────────────────────────────────────────────────
let rankingsSort = { col: 'wRC_plus', asc: false };

function renderTeamRankings() {
  const type = document.getElementById('rankingTypeFilter').value;
  const selDivs = getSelectedDivs('rankDiv');

  const teams = Object.keys(TM).filter(team => !selDivs || selDivs.includes(TM[team]?.div)).map(team => {
    const tp  = AP.filter(p => p.team === team);
    const tPA = tp.reduce((s,p) => s+p.PA, 0);
    const twOBA = tPA > 0
      ? (0.7*(tp.reduce((s,p)=>s+p.BB+p.HBP,0)) + 0.9*(tp.reduce((s,p)=>s+p.B1,0)) + 1.3*(tp.reduce((s,p)=>s+p.B2,0)) + 1.6*(tp.reduce((s,p)=>s+p.B3,0)) + 2*(tp.reduce((s,p)=>s+p.HR,0))) / tPA
      : 0;
    const wavg = (k) => tPA > 0 ? tp.reduce((s,p)=>s+(p[k]*p.PA),0)/tPA : 0;
    const pitchers = PP.filter(p => p.team === team);
    const tIP   = pitchers.reduce((s,p)=>s+p.IP,0);
    const tERA  = tIP > 0 ? (pitchers.reduce((s,p)=>s+p.ER,0)/tIP)*7 : 0;
    const tFIP  = tIP > 0 ? ((3*(pitchers.reduce((s,p)=>s+p.BB+p.HB,0)) - 2*(pitchers.reduce((s,p)=>s+p.K,0)))/tIP)+3.10 : 0;
    const tWHIP = tIP > 0 ? (pitchers.reduce((s,p)=>s+p.BB+p.H,0))/tIP : 0;
    const tK7   = tIP > 0 ? (pitchers.reduce((s,p)=>s+p.K,0)/tIP)*7 : 0;
    const tBB7  = tIP > 0 ? (pitchers.reduce((s,p)=>s+p.BB,0)/tIP)*7 : 0;
    const tWAR  = pitchers.reduce((s,p)=>s+p.WAR,0);
    return {
      team,
      m: TM[team],
      wRC_plus: Math.round(((twOBA-0.353)/1.12+0.177)/0.177*100),
      wOBA: twOBA,
      AVG: wavg('AVG'),
      OBP: wavg('OBP'),
      SLG: wavg('SLG'),
      OPS: wavg('OPS'),
      ERA: tERA, FIP: tFIP, WHIP: tWHIP,
      K7: tK7, BB7: tBB7, WAR: tWAR, IP: tIP,
    };
  });

  const hitCols = [
    { key:'wRC_plus', label:'wRC+',  fmt:v=>Math.round(v),    lowerBetter:false },
    { key:'wOBA',     label:'wOBA',  fmt:v=>v.toFixed(3).replace(/^0/,''), lowerBetter:false },
    { key:'OPS',      label:'OPS',   fmt:v=>v.toFixed(3),     lowerBetter:false },
    { key:'AVG',      label:'AVG',   fmt:v=>v.toFixed(3).replace(/^0/,''), lowerBetter:false },
    { key:'OBP',      label:'OBP',   fmt:v=>v.toFixed(3).replace(/^0/,''), lowerBetter:false },
    { key:'SLG',      label:'SLG',   fmt:v=>v.toFixed(3).replace(/^0/,''), lowerBetter:false },
  ];
  const pitCols = [
    { key:'ERA',  label:'ERA',  fmt:v=>v.toFixed(2), lowerBetter:true  },
    { key:'FIP',  label:'FIP',  fmt:v=>v.toFixed(2), lowerBetter:true  },
    { key:'WHIP', label:'WHIP', fmt:v=>v.toFixed(2), lowerBetter:true  },
    { key:'K7',   label:'K/7',  fmt:v=>v.toFixed(2), lowerBetter:false },
    { key:'BB7',  label:'BB/7', fmt:v=>v.toFixed(2), lowerBetter:true  },
    { key:'WAR',  label:'WAR',  fmt:v=>v.toFixed(1), lowerBetter:false },
    { key:'IP',   label:'IP',   fmt:v=>v.toFixed(1), lowerBetter:false },
  ];

  const cols = type === 'hitting' ? hitCols : pitCols;
  const defaultSort = type === 'hitting' ? 'wRC_plus' : 'ERA';
  if (!cols.find(c=>c.key===rankingsSort.col)) {
    rankingsSort = { col: defaultSort, asc: type !== 'hitting' };
  }

  const sortCol = cols.find(c=>c.key===rankingsSort.col) || cols[0];
  const sorted = [...teams].sort((a,b) =>
    rankingsSort.asc ? a[rankingsSort.col]-b[rankingsSort.col] : b[rankingsSort.col]-a[rankingsSort.col]
  );

  const sortArrow = rankingsSort.asc ? ' ▴' : ' ▾';

  document.getElementById('rankingsHead').innerHTML = `<tr>
    <th style="width:28px">#</th>
    <th>Team</th>
    ${cols.map(c => `<th class="num${c.key===rankingsSort.col?' rankings-sort-active':''}" style="cursor:pointer" onclick="sortRankings('${c.key}',${c.lowerBetter})">${c.label}${c.key===rankingsSort.col?sortArrow:''}</th>`).join('')}
  </tr>`;

  document.getElementById('rankingsBody').innerHTML = sorted.map((t,i) => `
    <tr onclick="showTeam('${t.team}','team-rankings')">
      <td style="font-family:'Outfit',sans-serif;font-weight:700;color:${i<3?'var(--accent)':'var(--muted)'}">${i+1}</td>
      <td>
        <div style="display:flex;align-items:center;gap:8px">
          ${t.m?.logo ? `<img src="${t.m.logo}" width="22" height="22" style="object-fit:contain;border-radius:2px">` : ''}
          <span style="font-family:'Outfit',sans-serif;font-weight:600;color:${t.m?.t||'var(--text)'}">${t.team}</span>
          <span style="font-size:11px;color:var(--muted)">${t.m?.mascot||''}</span>
        </div>
      </td>
      ${cols.map(c => {
        const v = t[c.key];
        const isSort = c.key === rankingsSort.col;
        return `<td class="num" style="${isSort?'font-weight:700;color:var(--accent)':''}">${isFinite(v)?c.fmt(v):'—'}</td>`;
      }).join('')}
    </tr>`).join('');
}

function sortRankings(col, lowerBetter) {
  if (rankingsSort.col === col) {
    rankingsSort.asc = !rankingsSort.asc;
  } else {
    rankingsSort = { col, asc: lowerBetter };
  }
  renderTeamRankings();
}

// ── STANDINGS ─────────────────────────────────────────────────────────────────
function teamStandingsRow(team) {
  const sched    = (typeof SCHEDULES !== 'undefined' && SCHEDULES[team]) || {};
  const games    = sched.games || [];
  const W        = sched.wins   || 0;
  const L        = sched.losses || 0;
  const G        = W + L;

  // Runs scored / allowed from game scores
  let RS = 0, RA = 0;
  games.forEach(g => {
    if (g.score && g.outcome) {
      const parts = g.score.split('-').map(Number);
      if (parts.length === 2 && !isNaN(parts[0]) && !isNaN(parts[1])) {
        // nj.com shows winning score first — so W = parts[0] is team, L = parts[0] is opponent
        if (g.outcome === 'W') { RS += parts[0]; RA += parts[1]; }
        else                   { RS += parts[1]; RA += parts[0]; }
      }
    }
  });

  const wpct  = G > 0 ? W / G : 0;
  const rdiff = RS - RA;
  const raPG  = G > 0 ? RA / G : 0;
  const rsPG  = G > 0 ? RS / G : 0;

  // Pythagorean expected record (exponent 1.83)
  const EXP = 1.83;
  const pythWpct = (RS + RA) > 0
    ? Math.pow(RS, EXP) / (Math.pow(RS, EXP) + Math.pow(RA, EXP))
    : 0.5;
  const pythW = Math.round(pythWpct * G);
  const pythL = G - pythW;

  return { team, W, L, G, wpct, RS, RA, rdiff, raPG, rsPG,
           pythW, pythL, pythWpct };
}

function renderStandings() {
  const confFilter = document.getElementById('standingsConfFilter')?.value?.toLowerCase() || '';
  const ALL_CONFS  = [...new Set(Object.values(TM).map(m => m.div).filter(Boolean))].sort();
  const DIVISIONS  = confFilter
    ? ALL_CONFS.filter(c => c.toLowerCase().includes(confFilter))
    : ALL_CONFS;

  const el = document.getElementById('standingsContent');
  if (!el) return;

  // Show last updated
  const upd = document.getElementById('standingsUpdated');
  if (upd && typeof DATA_UPDATED !== 'undefined') upd.textContent = `Updated ${DATA_UPDATED}`;

  el.innerHTML = DIVISIONS.map(div => {
    const divTeams = Object.keys(TM).filter(t => TM[t].div === div);
    const rows = divTeams.map(t => teamStandingsRow(t))
                         .sort((a, b) => b.wpct - a.wpct || b.rdiff - a.rdiff);

    const tableRows = rows.map((r, i) => {
      const m        = TM[r.team] || {};
      const wlClass  = r.wpct > 0.5 ? 'over-500' : r.wpct < 0.5 ? 'under-500' : 'even-500';
      const pdiff    = r.pythW - r.W;
      const pdiffStr = pdiff > 0 ? `+${pdiff}` : `${pdiff}`;
      const pdiffCls = pdiff > 0 ? 'pyth-diff-pos' : pdiff < 0 ? 'pyth-diff-neg' : 'pyth-diff-neu';

      return `<tr onclick="showTeam('${r.team}','standings')">
        <td>
          <div class="standings-team-cell">
            <span class="standings-pos ${i === 0 ? 'leader' : ''}">${i + 1}</span>
            ${m.logo ? `<img src="${m.logo}" width="22" height="22" style="object-fit:contain;border-radius:2px;flex-shrink:0">` : ''}
            <span class="standings-team-name" style="color:${m.t || 'var(--text)'}">${r.team}</span>
          </div>
        </td>
        <td class="num">
          <span class="standings-record ${wlClass}">${r.W}-${r.L}</span>
        </td>
        <td class="num" style="font-variant-numeric:tabular-nums">${r.wpct.toFixed(3).replace(/^0/,'')}</td>
        <td class="num" style="color:${r.rdiff > 0 ? '#4ade80' : r.rdiff < 0 ? '#f87171' : 'var(--muted2)'}">
          ${r.rdiff > 0 ? '+' : ''}${r.rdiff}
        </td>
        <td class="num" style="color:var(--muted2)">${r.rsPG.toFixed(2)}</td>
        <td class="num" style="color:var(--muted2)">${r.raPG.toFixed(2)}</td>
        <td class="num">
          <span style="font-family:'Bebas Neue',sans-serif;font-size:14px">${r.pythW}-${r.pythL}</span>
          <span class="${pdiffCls}" style="margin-left:5px">(${pdiffStr})</span>
        </td>
      </tr>`;
    }).join('');

    return `<div class="standings-division">
      <div class="standings-division-header">
        <span class="standings-division-name">${div}</span>
        <span class="standings-division-sub">${rows.length} teams</span>
      </div>
      <table class="standings-table">
        <thead><tr>
          <th>Team</th>
          <th class="num">Record</th>
          <th class="num" title="Win Percentage">PCT</th>
          <th class="num" title="Run Differential">RDIFF</th>
          <th class="num" title="Runs Scored per Game">RS/G</th>
          <th class="num" title="Runs Allowed per Game">RA/G</th>
          <th class="num" title="Pythagorean Expected Record (RS^1.83 / (RS^1.83 + RA^1.83)) — difference from actual in parentheses">PYTH</th>
        </tr></thead>
        <tbody>${tableRows}</tbody>
      </table>
    </div>`;
  }).join('');
}

// ── INIT ───────────────────────────────────────────────────────────────────────
normalizePlayers();
setupPlayerScore();
showLastUpdated();
buildDivFilters();
buildTeamFilters();
renderHitTable();
renderPitchTable();
renderTeamsGrid();
buildTeamsNav();
renderHome();
renderTeamRankings();
renderStandings();
